### ISSUE TITLE
Add support for autoload tasks

### ISSUE THREAD

**Issue by michel-cf** [gabops/ansible-role-appoptics#9] opened 2021-02-10 09:31 UTC
The documentation for tomcat monitoring does not seem to mention it, but the config should be in the tasks-autoload.d directory.

This should be added in a similar way as tasks and plugins.

**Comment by gabops** [comment] 2021-02-10 17:06
Hello there!

Thank you very much for your contribution. I had a look and it seems all right. The build is just failing apparently for some extra lines on the defaults file. Happy to merge once that is fixed and the build success.

Regards.

**Comment by michel-cf** [comment] 2021-02-12 10:23
I fixed the defaults yaml file but the build fails now on something else, and I have no idea what it is

> --> Action: 'idempotence'
ERROR: Idempotence test failed because of the following tasks:
> * [appoptics-molecule-instance-01] => ansible-role-appoptics : Configure Appoptics service
An error occurred during the test sequence action: 'idempotence'. Cleaning up.

If this is something because of what I added please inform me about what the issue is.
Also, the CentOS 6 build failed because of - what I think is - a docker build issue.

**Comment by gabops** [comment] 2021-04-03 09:31
The issue is not related with the change you introduced. I merged it and I will work on a fix. Thank you again.


Regards.

**Closed by gabops** 2021-04-03 09:31 UTC
